# Generated by Django 4.1.2 on 2022-10-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('technical_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('clear_name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
