# Generated by Django 4.1.2 on 2022-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excludarr', '0002_generalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
