# Generated by Django 4.1.2 on 2022-11-05 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excludarr', '0003_alter_generalsettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarrSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=32)),
                ('verify_ssl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonarrSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=32)),
                ('verify_ssl', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
