# Generated by Django 4.1.2 on 2022-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excludarr', '0005_radarrsettings_user_sonarrsettings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radarr_id', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('tmdb_id', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=20)),
                ('sizeOnDisk', models.BigIntegerField()),
                ('year', models.IntegerField()),
                ('quality_available', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=512)),
                ('tags', models.CharField(max_length=1024)),
                ('monitored', models.BooleanField()),
            ],
        ),
    ]
