# Generated by Django 4.1.2 on 2022-11-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excludarr', '0007_movies_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='sizeOnDisk',
            new_name='size',
        ),
    ]
