# Generated by Django 4.1.2 on 2022-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excludarr', '0009_alter_movies_imdb_id_alter_movies_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
    ]
