---

version: '3'

services:
  excludarr:
    container_name: excludarr
    restart: unless-stopped
    build: .

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - excludarr
 